# Generated by Django 5.0.7 on 2024-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("link", models.URLField()),
            ],
        ),
    ]
