# Generated by Django 5.0.7 on 2024-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0003_rename_certificates_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="certificates/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.AlterField(
            model_name="home",
            name="greetings_1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="home",
            name="greetings_2",
            field=models.CharField(max_length=200),
        ),
    ]
