# Generated by Django 5.0.7 on 2024-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0005_projects_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="video",
            field=models.FileField(
                blank=True,
                default="default_video.mp4",
                null=True,
                upload_to="projects/",
            ),
        ),
    ]
