# Generated by Django 5.0.6 on 2024-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0006_alter_projects_image_alter_projects_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
