# Generated by Django 5.0.7 on 2024-07-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0007_alter_about_profile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="picture",
        ),
    ]
