# Generated by Django 5.0.7 on 2024-07-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0008_remove_home_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="greetings_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
