# Generated by Django 5.0.7 on 2024-07-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0009_alter_home_greetings_2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
