# Generated by Django 5.0.6 on 2024-08-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0010_delete_portfolio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="link",
        ),
    ]
