# Generated by Django 5.0.6 on 2024-08-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0011_remove_projects_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="video",
            field=models.TextField(
                blank=True, help_text="Add the embed link of the video", null=True
            ),
        ),
    ]
