# Generated by Django 5.0.6 on 2024-08-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0012_alter_projects_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="image",
        ),
    ]
