# Generated by Django 5.0.6 on 2024-08-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0013_remove_projects_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="video",
        ),
        migrations.AddField(
            model_name="projects",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="projects",
            name="link",
            field=models.URLField(default="http://example.com"),
        ),
        migrations.AddField(
            model_name="projects",
            name="video_embed_link",
            field=models.TextField(
                blank=True, help_text="Add the embed link of the video", null=True
            ),
        ),
    ]
