# Generated by Django 5.0.6 on 2024-08-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0014_remove_projects_video_projects_image_projects_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="video_embed_link",
            new_name="video",
        ),
    ]
