# Generated by Django 5.0.6 on 2024-08-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0015_rename_video_embed_link_projects_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="image",
        ),
    ]
