# Generated by Django 5.0.6 on 2024-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elnara", "0016_remove_projects_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificates",
            name="title",
            field=models.TextField(default="title name", max_length=250),
        ),
    ]
